name: xnat
services:
  xnat-web:
    # NOTE: Uncomment this to test an already built image
    # image: ghcr.io/brown-bnc/xnat:1.10.1-batch-transfer
    build:
      context: .
    ports:
      - "8000:8000"
      - "8080:8080"
      - "8104:8104"
    env_file: ./k8s/.env
    volumes:
      # Enable plugins
      - ./k8s/config/ldap-provider.properties:/data/xnat/home/config/auth/ldap-provider.properties
      - ./k8s/config/oidc-provider.properties:/data/xnat/home/config/auth/oidc-provider.properties
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "localhost:8000/"]
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file: ./k8s/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
