version: "3.5"
services:
  xnat:
    build:
      context: .
      args:
        XNAT_VERSION: 1.8.0-TIP-RC3
    image: ghcr.io/brown-bnc/xnat:1.8.0-TIP-RC3
    ports:
      - "8000:8000"
      - "8080:8080"
      - "8104:8104"
    environment:
      CATALINA_OPTS: "-Xms128m -Xmx1024m"
      POSTGRES_HOST: "postgres"
      POSTGRES_DB: "xnat"
      POSTGRES_USER: "xnat"
      POSTGRES_PASSWORD: "xnat"
      LDAP_HOST: "${LDAP_HOST}"
      LDAP_USER: "${LDAP_USER}"
      LDAP_PASSWORD: "${LDAP_PASSWORD}"
      LDAP_SEARCH_BASE: "${LDAP_SEARCH_BASE}"
      LDAP_SEARCH_FILTER: "${LDAP_SEARCH_FILTER}"
  postgres:
    image: postgres:9
    environment:
      POSTGRES_DB: "xnat"
      POSTGRES_USER: "xnat"
      POSTGRES_PASSWORD: "xnat"
