apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: xnat
resources:
- app.yaml
- db.yaml
configMapGenerator:
- name: app-config
  literals:
  - CATALINA_OPTS=-Xms128m -Xmx1024m
  - POSTGRES_HOST=postgres
  - POSTGRES_PORT=5432
  - POSTGRES_DB=xnat
  - POSTGRES_USER=xnat
  - POSTGRES_PASSWORD=xnat
  - XNAT_SITE_URL=http://xnat.local
  - XNAT_ADMIN_EMAIL=admin@xnat.local
- name: db-config
  literals:
  - POSTGRES_DB=xnat
  - POSTGRES_USER=xnat
  - POSTGRES_PASSWORD=xnat
secretGenerator:
- name: ldap-config
  env: ldap.env
