apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: xnat
namePrefix: local-
resources:
  - app.yaml
  - db.yaml
  - namespace.yaml
secretGenerator:
  - name: environment
    envs:
      - .env
  - name: ldap-config
    files:
      - config/ldap-provider.properties
  - name: oidc-config
    files:
      - config/oidc-provider.properties
