name: Build Docker image
on:
  push:
  release:
    types: [created, edited, published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: bnc-it
          password: ${{ secrets.CR_PAT }}
      - name: Save release image name
        run: |
          echo "RELEASE_IMAGE=$(cat docker-compose.yaml | sed -n 's/^[ ]*image: \(ghcr.*$\)/\1/p')" >> $GITHUB_ENV
      - name: Save dev image name
        run: |
          echo "DEV_IMAGE=$(cat docker-compose.yaml | sed -n 's/^[ ]*image: \(ghcr.*\):.*$/\1/p')" >> $GITHUB_ENV
      - name: Build Docker image
        run: docker-compose build
      - name: Push dev image to GitHub Container Registry
        run: |
          docker tag "${RELEASE_IMAGE}" "${DEV_IMAGE}"
          docker push "${DEV_IMAGE}"
      - name: Push release image to GitHub Container Registry
        if: ${{ github.event_name == 'release' }}
        run: |
          docker push "${RELEASE_IMAGE}" 
